In [79]:
import pandas as pd
import numpy as np

data = pd.read_csv('因子報酬敘述統計/ Strong Momentum_factor_return_adj.csv').drop('Unnamed: 0',axis=1)
data = data.set_index('Date')


#半衰期(half-life)權重
def half(t,a):  #t=half-life, a=sample size
     lambd=0.5**(1/t)
     weightlist=[]
     for i in range(a-1,-1,-1): #a=539,b=-1,i=539、538、...0
         halflife=lambd**i
         weightlist.append(halflife)
     weightlist = np.array(weightlist)/sum(weightlist)   
     return weightlist

delta_weilist=[]
for i in range(1,16):
    delta_wei=(1-(i/(1+15)))
    delta_weilist.append(delta_wei)
    
#sam_size=1500
sam_size=540
#half=125
half_ =45 

In [80]:
data

Market  Computing  Culture & Entertainment  Currency      DeFi  \
Date                                                                           
2018-02-01 -0.066537  -0.005161                -0.023902  0.006529 -0.170333   
2018-02-02  0.054181  -0.003523                -0.007160  0.003610  0.111393   
2018-02-03 -0.109452  -0.020020                 0.064769 -0.003678  0.067482   
2018-02-04 -0.177340   0.007646                 0.075094 -0.008588 -0.049981   
2018-02-05  0.109105  -0.043942                -0.025162  0.009593 -0.413518   
...              ...        ...                      ...       ...       ...   
2022-11-22  0.036798  -0.013492                -0.001098 -0.008390  0.059580   
2022-11-23 -0.099987   0.004846                -0.016815  0.025119 -0.010318   
2022-11-24 -0.142811  -0.022162                 0.004139 -0.004312 -0.001729   
2022-11-25  0.074545   0.001236                -0.016283  0.008654  0.024695   
2022-11-26  0.116829  -0.003650                -0.004426  0.003271 -0.000511   

            Digitization  Smart Contract Platform  centrality  liquidity  \
Date                                                                       
2018-02-01      0.012044                -0.028599   -0.004717  -0.070419   
2018-02-02     -0.057310                -0.013510    0.031366   0.107302   
2018-02-03     -0.022885                 0.015517    0.023611   0.034100   
2018-02-04     -0.013548                 0.028185    0.057618  -0.056210   
2018-02-05      0.009899                -0.017546    0.048405  -0.267441   
...                  ...                      ...         ...        ...   
2022-11-22      0.031697                -0.011923    0.008432  -0.001878   
2022-11-23     -0.015137                -0.006960    0.002013   0.042829   
2022-11-24     -0.011141                 0.015632    0.000899  -0.005057   
2022-11-25      0.014583                -0.003947   -0.000847  -0.045354   
2022-11-26      0.004301                 0.001566    0.010393  -0.372995   

            momentum      size  volatility  
Date                                        
2018-02-01 -0.015923  0.002434   -0.019067  
2018-02-02 -0.013825 -0.025460    0.000082  
2018-02-03 -0.012323  0.010774   -0.007786  
2018-02-04 -0.014131  0.026514    0.004605  
2018-02-05 -0.006181 -0.011115    0.035555  
...              ...       ...         ...  
2022-11-22 -0.003813 -0.002067   -0.013117  
2022-11-23 -0.019767 -0.014746    0.061044  
2022-11-24  0.007884 -0.051500   -0.037726  
2022-11-25 -0.011272  0.026600    0.006157  
2022-11-26  0.007158  0.030679   -0.024000  

[1760 rows x 12 columns]

In [81]:
data.fillna(0,inplace=True)
data

Market  Computing  Culture & Entertainment  Currency      DeFi  \
Date                                                                           
2018-02-01 -0.066537  -0.005161                -0.023902  0.006529 -0.170333   
2018-02-02  0.054181  -0.003523                -0.007160  0.003610  0.111393   
2018-02-03 -0.109452  -0.020020                 0.064769 -0.003678  0.067482   
2018-02-04 -0.177340   0.007646                 0.075094 -0.008588 -0.049981   
2018-02-05  0.109105  -0.043942                -0.025162  0.009593 -0.413518   
...              ...        ...                      ...       ...       ...   
2022-11-22  0.036798  -0.013492                -0.001098 -0.008390  0.059580   
2022-11-23 -0.099987   0.004846                -0.016815  0.025119 -0.010318   
2022-11-24 -0.142811  -0.022162                 0.004139 -0.004312 -0.001729   
2022-11-25  0.074545   0.001236                -0.016283  0.008654  0.024695   
2022-11-26  0.116829  -0.003650                -0.004426  0.003271 -0.000511   

            Digitization  Smart Contract Platform  centrality  liquidity  \
Date                                                                       
2018-02-01      0.012044                -0.028599   -0.004717  -0.070419   
2018-02-02     -0.057310                -0.013510    0.031366   0.107302   
2018-02-03     -0.022885                 0.015517    0.023611   0.034100   
2018-02-04     -0.013548                 0.028185    0.057618  -0.056210   
2018-02-05      0.009899                -0.017546    0.048405  -0.267441   
...                  ...                      ...         ...        ...   
2022-11-22      0.031697                -0.011923    0.008432  -0.001878   
2022-11-23     -0.015137                -0.006960    0.002013   0.042829   
2022-11-24     -0.011141                 0.015632    0.000899  -0.005057   
2022-11-25      0.014583                -0.003947   -0.000847  -0.045354   
2022-11-26      0.004301                 0.001566    0.010393  -0.372995   

            momentum      size  volatility  
Date                                        
2018-02-01 -0.015923  0.002434   -0.019067  
2018-02-02 -0.013825 -0.025460    0.000082  
2018-02-03 -0.012323  0.010774   -0.007786  
2018-02-04 -0.014131  0.026514    0.004605  
2018-02-05 -0.006181 -0.011115    0.035555  
...              ...       ...         ...  
2022-11-22 -0.003813 -0.002067   -0.013117  
2022-11-23 -0.019767 -0.014746    0.061044  
2022-11-24  0.007884 -0.051500   -0.037726  
2022-11-25 -0.011272  0.026600    0.006157  
2022-11-26  0.007158  0.030679   -0.024000  

[1760 rows x 12 columns]

In [82]:
sum(half(half_,sam_size))

1.0

In [83]:
mat = data.shape[1]

deltalist_pp=[]
deltalist_mm=[]
for day in range(data.shape[0]-sam_size):
    data1=data.iloc[0+day:sam_size+day]
    deltalist_m=[]
    deltalist_p=[]
    for i in range(1,16): 
        Wv = np.zeros((sam_size,sam_size))
        Wv[np.arange(sam_size), np.arange(sam_size)] = half(half_,sam_size)
        Wc = np.zeros((sam_size,sam_size))
        Wc[np.arange(sam_size), np.arange(sam_size)] = half(half_,sam_size)
        Wv = Wv[i:,i:]
        Wc = Wc[i:,i:]
        M1 = data1.shift(i)[i:len(data1)] #0-538
        M2 = data1[i:len(data1)]          #1-539
        U1 = np.zeros((mat,mat))
        U1[np.arange(mat), np.arange(mat)] = 1
        U2 = np.ones((mat,mat))
        U2[np.arange(mat), np.arange(mat)] = 0
        Cd_p = Wv.dot(M1).T.dot(M2)*U1 + Wc.dot(M1).T.dot(M2)*U2
        Cd_m = Cd_p.T
        deltalist_p.append(Cd_p) 
        deltalist_m.append(Cd_m)
    deltalist_pp.append([data.index[sam_size+day],deltalist_p])
    deltalist_mm.append([data.index[sam_size+day],deltalist_m])
    print(day)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [84]:
port_varlist=[]
for day in range(data.shape[0]-sam_size):
    data1=data.iloc[0+day:sam_size+day]
    data2=data1-data1.describe().loc['mean']
     
    #EUE3S_var
    varT=(data2.T*half(half_,sam_size)).dot(data2)
    varT=varT/sum(half(half_,sam_size))
    var=np.diag(varT)
    
    #EUE3S_cor
    corT=(data2.T*half(half_,sam_size)).dot(data2)
    corT=corT/sum(half(half_,sam_size))
    #Cd
    Cd=corT.values.copy()
    np.fill_diagonal(Cd, var)
    #CdT=pd.DataFrame(Cd)
    port_varlist.append([data.index[sam_size+day],Cd])
    print(day) #0、1、...2262 #0、1、...1302

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [85]:
Cmlist=[]    
for day in range(data.shape[0]-sam_size):  
    delta_times=[]
    for i in range(15): 
        d_times=delta_weilist[i]*( deltalist_pp[day][1][i]+ deltalist_mm[day][1][i] )
        delta_times.append(d_times)
    delta_sum=sum(delta_times)   
    Cm=(port_varlist[day][1] + delta_sum)*22
    Cmlist.append([data.index[sam_size+day], Cm])

In [86]:
len(Cmlist)

1220

In [87]:
for i in range(data.shape[0]-sam_size):
    a=Cmlist[i][1]
    np.save('Common Factor Risk_Long\Cm_Strong Momentum'+str(i)+'.npy',a)

In [99]:
#以下測試
Wv = np.zeros((540,540))
Wv[np.arange(540), np.arange(540)] = half(90,sam_size)
Wc = np.zeros((540,540))
Wc[np.arange(540), np.arange(540)] = half(180,sam_size)
Wv = Wv[i:,i:]
Wc = Wc[i:,i:]
M1 = data1.shift(i)[i:len(data1)] #0-538
M2 = data1[i:len(data1)]          #1-539
U1 = np.zeros((41,41))
U1[np.arange(41), np.arange(41)] = 1
U2 = np.ones((41,41))
U2[np.arange(41), np.arange(41)] = 0
Cd_p = Wv.dot(M1).T.dot(M2)*U1 + Wc.dot(M1).T.dot(M2)*U2
Cd_p

array([[ 1.16782686e-04, -6.93386420e-04, -1.61646452e-03, ...,
        -5.15561688e-05, -5.95811362e-05,  1.10203937e-04],
       [-6.46803087e-04,  4.62103615e-04,  1.18628714e-03, ...,
        -1.93425541e-05, -9.44618787e-05, -9.19979422e-07],
       [-4.46928436e-04,  7.53975971e-04,  1.14675779e-03, ...,
        -4.27555865e-05, -1.30674957e-05,  1.00114603e-04],
       ...,
       [ 3.69579124e-05,  2.32214584e-05,  5.81053500e-06, ...,
         2.20004595e-07,  3.98279621e-06,  1.94578296e-07],
       [ 4.48448618e-05,  8.37088039e-05,  3.01357074e-07, ...,
        -8.82074455e-07,  3.98149545e-07, -4.48184465e-06],
       [ 6.45372509e-05,  1.62335664e-04,  5.30904000e-05, ...,
         5.34331161e-06,  4.40111886e-06,  7.54263937e-06]])

In [35]:
Cmlist=[]     
for i in range(data.shape[0]-sam_size):
    a1=np.load('Common Factor Risk_Long\Cm_Small Size'+str(i)+'.npy')
    Cmlist.append(a1)

In [24]:
Cmlist[0][2]

array([ 0.11817584, -0.00265491,  0.01015395, -0.00122186, -0.00286257,
       -0.00346625,  0.00067676,  0.00180999, -0.00342267, -0.00105511,
        0.035161  , -0.00066851])

In [78]:
deltalist_pp[1418][1][1]

array([[ 3.73330125e-06,  5.75869005e-06,  1.32752008e-06, ...,
         6.31961150e-07, -1.02292191e-06,  2.08850139e-07],
       [ 6.28848119e-06, -1.22672700e-07, -5.06351588e-07, ...,
        -1.02862938e-06, -3.94503905e-07, -1.00145361e-06],
       [-1.29319621e-06,  1.49495257e-06, -7.79874521e-08, ...,
         1.56113786e-07, -1.16465013e-06,  4.62279823e-07],
       ...,
       [ 2.02528306e-06,  3.02598227e-07,  4.13563129e-07, ...,
         2.28594914e-07, -1.52223880e-07,  1.45305613e-07],
       [-5.32970255e-07, -7.00866815e-07, -2.66483829e-07, ...,
        -4.43577154e-08,  1.41073302e-07,  4.08913782e-09],
       [ 8.69713885e-07, -1.50757842e-07,  1.94892320e-07, ...,
         3.21157882e-08,  6.36183010e-08, -2.61489310e-08]])

In [79]:
port_varlist[0][1]

array([[ 9.86214754e-05,  4.89980586e-07, -5.29837775e-06, ...,
         1.16205717e-06, -4.53314608e-07, -1.36602564e-06],
       [ 4.89980586e-07,  4.07517074e-05, -6.78219617e-07, ...,
        -8.59099202e-08, -8.41368130e-07,  2.79443543e-07],
       [-5.29837775e-06, -6.78219617e-07,  2.17220243e-05, ...,
         5.64174952e-07, -3.98651320e-07,  2.53155970e-08],
       ...,
       [ 1.16205717e-06, -8.59099202e-08,  5.64174952e-07, ...,
         1.73518880e-06,  1.04517700e-08, -1.16221808e-08],
       [-4.53314608e-07, -8.41368130e-07, -3.98651320e-07, ...,
         1.04517700e-08,  1.37700805e-06, -1.30265104e-08],
       [-1.36602564e-06,  2.79443543e-07,  2.53155970e-08, ...,
        -1.16221808e-08, -1.30265104e-08,  7.82204249e-07]])